### ISSUE TITLE
Determine if it is allowed to use both commands and events in the same queue

### ISSUE THREAD

**Issue by mikederksen** [mikederksen/TeamRemi#1]
An `[Queue ("QueueName")]` attribute can be used to mark a class to listen to a queue
- `[Topic ("Routing.Key")]` attributes can be used to mark a method for listening to incoming events
-`[Command("CommandKey")]` attributes can be used to mark a method for listening to incoming commands.

Should it be allowed to have both a Topic and a Command attribute for the same Queue?

**Comment by TiruYasha** [comment]
I don't think this should be allowed. As stated in the rabbitMq documentation of RPC: "the client creates an anonymous exclusive callback queue". Events should not be in the same queue as RPC commands.

**Comment by mikederksen** [comment]
Fair enough
